
services:
  - type: web
    name: versatile-share
    env: node
    buildCommand: ./build.sh
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS  
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      # AWS S3 Configuration (for file uploads)
      - key: AWS_S3_BUCKET_NAME
        value: versatileshare
      - key: AWS_S3_REGION
        value: us-east-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
